// <auto-generated />
namespace ASPODES.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Person_Status_Name_Nullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Person_Status_Name_Nullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201710131707231_Person_Status_Name_Nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
