// <auto-generated />
namespace ASPODES.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LoginLog_Roles_Length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoginLog_Roles_Length));
        
        string IMigrationMetadata.Id
        {
            get { return "201707182242547_LoginLog_Roles_Length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
