// <auto-generated />
namespace ASPODES.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Annpuncement_Publisher_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Annpuncement_Publisher_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201711060226156_Annpuncement_Publisher_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
