// <auto-generated />
namespace ASPODES.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_ExpertFields_Map : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_ExpertFields_Map));
        
        string IMigrationMetadata.Id
        {
            get { return "201710140107411_User_ExpertFields_Map"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
