// <auto-generated />
namespace ASPODES.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20171031Empty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20171031Empty));
        
        string IMigrationMetadata.Id
        {
            get { return "201710310248406_20171031-Empty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
