// <auto-generated />
namespace ASPODES.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Del_TemplateReson_FK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Del_TemplateReson_FK));
        
        string IMigrationMetadata.Id
        {
            get { return "201708150726276_Del_TemplateReson_FK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
